import type { EncodingCategory, EncodingSpec } from "./types";
import { base16LowerEngine, base16UpperEngine } from "./base16";
import { base32Engine, base32HexEngine, crockfordBase32Engine, zBase32Engine } from "./base32";
import { base45Engine, BASE45_ALPHABET } from "./base45";
import { base36Engine, base58BtcEngine, base58FlickrEngine, base62Engine, BASE36, BASE58_BTC, BASE58_FLICKR, BASE62 } from "./base58";
import { base58CheckEngine } from "./base58check";
import { base64Engine, base64MimeEngine, base64PemBodyEngine, base64UrlEngine, base64UrlNoPadEngine } from "./base64";
import { adobeAscii85Engine, ascii85Engine, ASCII85_ALPHABET, rfc1924Engine, RFC1924_ALPHABET, z85Engine, Z85_ALPHABET } from "./base85";
import { base91Engine, BASE91_ALPHABET } from "./base91";
import { makeRarePackageEngine } from "./rare";

export const categoryOrder: EncodingCategory[] = [
  "Official standards",
  "Base32 family",
  "Base58 / crypto",
  "Base85 family",
  "Dense printable encodings",
  "Rare Unicode lab",
  "Custom / numeric"
];

export const encodingSpecs: EncodingSpec[] = [
  {
    id: "base16-rfc4648",
    name: "Base16 / Hexadecimal — RFC 4648 uppercase",
    shortName: "Base16",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 4648, Section 8",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "0123456789ABCDEF",
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["hex", "hexadecimal", "base16 upper"],
    tags: ["official", "bytes", "hash", "developer"],
    summary: "Canonical RFC 4648 Base16 using uppercase hexadecimal digits.",
    canonicalRules: ["No padding is used.", "Each byte becomes exactly two hexadecimal characters.", "Strict mode rejects lowercase a-f so canonical output stays uppercase."],
    examples: [{ plain: "hello", encoded: "68656C6C6F" }],
    engine: base16UpperEngine
  },
  {
    id: "base16-lowercase",
    name: "Base16 / Hexadecimal — lowercase compatibility",
    shortName: "Hex lower",
    category: "Official standards",
    status: "De facto standard",
    standard: "RFC 4648 algorithm with lowercase presentation",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "0123456789abcdef",
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["lowercase hex", "sha style hex"],
    tags: ["developer", "hash", "compatibility"],
    summary: "Lowercase hex is widely used in hashes and developer tools; the byte algorithm is identical to Base16.",
    canonicalRules: ["No padding is used.", "Each byte becomes exactly two hexadecimal characters.", "Strict mode rejects uppercase A-F for this lowercase profile."],
    examples: [{ plain: "hello", encoded: "68656c6c6f" }],
    engine: base16LowerEngine
  },
  {
    id: "base32-rfc4648",
    name: "Base32 — RFC 4648 padded",
    shortName: "Base32",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 4648, Section 6",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567",
    padding: "=",
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["rfc base32", "totp secret base32"],
    tags: ["official", "totp", "dns safe"],
    summary: "Canonical RFC 4648 Base32 with uppercase alphabet and '=' padding.",
    canonicalRules: ["Output is padded to a multiple of 8 characters when padding is enabled.", "Strict mode requires uppercase RFC alphabet symbols plus terminal padding.", "Line feeds are not inserted."],
    examples: [{ plain: "hello", encoded: "NBSWY3DP" }, { plain: "hello!", encoded: "NBSWY3DPEE======" }],
    engine: base32Engine
  },
  {
    id: "base32hex-rfc4648",
    name: "Base32hex — RFC 4648 Extended Hex Alphabet",
    shortName: "Base32hex",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 4648, Section 7",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUV",
    padding: "=",
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["extended hex base32"],
    tags: ["official", "dnssec"],
    summary: "RFC 4648 Base32 Extended Hex alphabet variant with '=' padding.",
    canonicalRules: ["Output is padded to a multiple of 8 characters when padding is enabled.", "Alphabet order is 0-9 then A-V.", "Line feeds are not inserted."],
    examples: [{ plain: "hello", encoded: "D1IMOR3F" }],
    engine: base32HexEngine
  },
  {
    id: "base64-rfc4648",
    name: "Base64 — RFC 4648 padded",
    shortName: "Base64",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 4648, Section 4",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    padding: "=",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["standard base64", "rfc base64"],
    tags: ["official", "web", "file", "api"],
    summary: "Canonical RFC 4648 Base64 with '+' and '/' alphabet and '=' padding.",
    canonicalRules: ["Output is padded to a multiple of 4 characters when padding is enabled.", "No line wrapping is inserted by this tool.", "Strict mode rejects characters outside the selected alphabet."],
    examples: [{ plain: "hello", encoded: "aGVsbG8=" }],
    engine: base64Engine
  },
  {
    id: "base64url-rfc4648",
    name: "Base64url — RFC 4648 URL and filename safe alphabet",
    shortName: "Base64url",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 4648, Section 5",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc4648",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
    padding: "=",
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["url safe base64", "jwt base64url"],
    tags: ["official", "url", "jwt", "web"],
    summary: "RFC 4648 URL-safe Base64 alphabet using '-' and '_' instead of '+' and '/'.",
    canonicalRules: ["Padding is supported and enabled by default.", "The alphabet is URL and filename safe.", "Strict mode rejects normal Base64 '+' and '/' characters."],
    examples: [{ plain: "hello", encoded: "aGVsbG8=" }, { plain: "hex: FBFF", inputMode: "hex", encoded: "-_8=" }],
    engine: base64UrlEngine
  },
  {
    id: "base64url-jose-rfc7515",
    name: "Base64url — JOSE/JWT unpadded profile",
    shortName: "Base64url no-pad",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 7515 / JOSE Base64url without padding",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc7515.html",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["jwt base64url", "jws base64url", "jose base64url", "base64url no padding"],
    tags: ["official", "jwt", "jose", "url", "no padding"],
    summary: "The JOSE/JWT profile uses Base64url encoding with all trailing '=' padding characters omitted.",
    canonicalRules: ["Encoder always omits '=' padding for this profile.", "Decoder accepts the unpadded Base64url length rules used by JOSE.", "The global padding toggle is ignored so this profile stays canonical."],
    examples: [{ plain: "hello", encoded: "aGVsbG8" }, { plain: "hex: FBFF", inputMode: "hex", encoded: "-_8" }],
    engine: base64UrlNoPadEngine
  },
  {
    id: "base64-mime-rfc2045",
    name: "MIME Base64 — RFC 2045 content-transfer profile",
    shortName: "MIME Base64",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 2045, Section 6.8",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2045.html",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    padding: "=",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["email base64", "mime content transfer encoding", "rfc 2045 base64"],
    tags: ["official", "email", "mime", "line wrapped"],
    summary: "Official MIME Base64 content-transfer encoding profile with canonical 76-character line wrapping.",
    canonicalRules: ["Encoder wraps output at 76 characters using CRLF line breaks.", "The alphabet and padding are the RFC 4648/Base64 alphabet used by MIME.", "Decoder ignores MIME whitespace while validating Base64 symbols."],
    examples: [{ plain: "hello", encoded: "aGVsbG8=" }],
    engine: base64MimeEngine
  },
  {
    id: "base64-pem-rfc7468",
    name: "PEM textual Base64 body — RFC 7468",
    shortName: "PEM Base64 body",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 7468 textual encoding body",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc7468.html",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    padding: "=",
    safeForUrls: false,
    supportsFiles: true,
    aliases: ["pem base64", "certificate base64", "rfc 7468"],
    tags: ["official", "pem", "certificate", "line wrapped"],
    summary: "Base64 body profile used inside RFC 7468 textual encodings such as certificates and keys.",
    canonicalRules: ["Encoder wraps the Base64 body at 64 characters.", "Decoder accepts pasted BEGIN/END armor lines and decodes the body.", "The tool does not invent a certificate/key label when encoding raw bytes."],
    examples: [{ plain: "hello", encoded: "aGVsbG8=" }],
    engine: base64PemBodyEngine
  },
  {
    id: "base45-rfc9285",
    name: "Base45 — RFC 9285",
    shortName: "Base45",
    category: "Official standards",
    status: "Official standard",
    standard: "RFC 9285",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc9285.html",
    alphabet: BASE45_ALPHABET,
    padding: null,
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["qr base45"],
    tags: ["official", "qr", "alphanumeric"],
    summary: "Base45 is an RFC-defined binary-to-text encoding designed around QR Code alphanumeric mode.",
    canonicalRules: ["Two input bytes become three Base45 characters.", "A final single input byte becomes two Base45 characters.", "No padding is used."],
    examples: [{ plain: "AB", encoded: "BB8" }, { plain: "Hello!!", encoded: "%69 VD92EX0" }],
    engine: base45Engine
  },
  {
    id: "crockford-base32",
    name: "Crockford Base32",
    shortName: "Crockford32",
    category: "Base32 family",
    status: "Published reference",
    standard: "Douglas Crockford Base32 specification",
    sourceUrl: "https://www.crockford.com/base32.html",
    alphabet: "0123456789ABCDEFGHJKMNPQRSTVWXYZ",
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["human base32", "crockford"],
    tags: ["human friendly", "codes", "ids"],
    summary: "A human-friendly Base32 variant designed to avoid ambiguous characters.",
    canonicalRules: ["No padding is used in this core implementation.", "Encoder emits uppercase symbols.", "Decoder supports common ambiguity aliases in non-strict mode."],
    examples: [{ plain: "hello", encoded: "D1JPRV3F" }],
    engine: crockfordBase32Engine
  },
  {
    id: "z-base-32",
    name: "z-base-32",
    shortName: "z-base-32",
    category: "Base32 family",
    status: "Published reference",
    standard: "z-base-32 human-oriented alphabet",
    sourceUrl: "https://philzimmermann.com/docs/human-oriented-base-32-encoding.txt",
    alphabet: "ybndrfg8ejkmcpqxot1uwisza345h769",
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["zbase32", "zimmermann base32"],
    tags: ["human friendly", "security"],
    summary: "A human-oriented Base32 alphabet used in some security and distributed-system contexts.",
    canonicalRules: ["No padding is used.", "Alphabet order is not RFC 4648-compatible.", "Strict mode rejects characters outside the z-base-32 alphabet."],
    examples: [{ plain: "hello", encoded: "pb1sa5dx" }],
    engine: zBase32Engine
  },
  {
    id: "base58btc",
    name: "Base58BTC — Bitcoin alphabet",
    shortName: "Base58BTC",
    category: "Base58 / crypto",
    status: "De facto standard",
    standard: "Bitcoin / Multibase base58btc alphabet",
    sourceUrl: "https://github.com/multiformats/multibase",
    alphabet: BASE58_BTC,
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["bitcoin base58", "ipfs base58btc"],
    tags: ["crypto", "multibase", "ids"],
    summary: "Bitcoin-style Base58 avoids visually confusing characters such as 0, O, I, and l.",
    canonicalRules: ["Leading zero bytes are encoded as leading '1' characters.", "No padding is used.", "This is a de facto ecosystem standard, not an IETF RFC."],
    examples: [{ plain: "hello", encoded: "Cn8eVZg" }],
    engine: base58BtcEngine
  },
  {
    id: "base58flickr",
    name: "Base58Flickr — Flickr alphabet",
    shortName: "Base58Flickr",
    category: "Base58 / crypto",
    status: "De facto standard",
    standard: "Flickr-style Base58 alphabet",
    sourceUrl: "https://github.com/multiformats/multibase",
    alphabet: BASE58_FLICKR,
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["flickr base58"],
    tags: ["ids", "url shortener"],
    summary: "Flickr-style Base58 uses a different mixed-case alphabet order than Base58BTC.",
    canonicalRules: ["Leading zero bytes are encoded as leading '1' characters.", "No padding is used.", "Do not mix this alphabet with Base58BTC."],
    examples: [{ plain: "hello", encoded: "cM8DuyF" }],
    engine: base58FlickrEngine
  },
  {
    id: "base58check",
    name: "Base58Check — Bitcoin checksum profile",
    shortName: "Base58Check",
    category: "Base58 / crypto",
    status: "De facto standard",
    standard: "Bitcoin Base58Check checksum convention",
    sourceUrl: "https://en.bitcoin.it/wiki/Base58Check_encoding",
    alphabet: BASE58_BTC,
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    recommended: true,
    aliases: ["bitcoin address encoding", "base58 checksum"],
    tags: ["crypto", "checksum", "address"],
    summary: "Base58BTC plus a four-byte double-SHA-256 checksum. This tool encodes/decodes payload bytes and verifies the checksum on decode.",
    canonicalRules: ["The checksum is the first four bytes of SHA256(SHA256(payload)).", "Decoding fails if checksum verification fails.", "Version bytes are treated as part of the payload so users can provide them explicitly."],
    examples: [{ plain: "hex: 00", inputMode: "hex", encoded: "1Wh4bh" }],
    engine: base58CheckEngine
  },
  {
    id: "ascii85",
    name: "Ascii85 — raw btoa-style Base85",
    shortName: "Ascii85",
    category: "Base85 family",
    status: "De facto standard",
    standard: "Ascii85 / btoa family",
    alphabet: ASCII85_ALPHABET,
    padding: "partial final block rule",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["base85", "btoa ascii85"],
    tags: ["base85", "legacy", "dense"],
    summary: "Classic Base85 using printable ASCII characters from '!' to 'u', without Adobe delimiters.",
    canonicalRules: ["Four bytes become five printable characters.", "A final partial byte group emits length + 1 encoded characters.", "The zero group shorthand 'z' is supported for compatibility."],
    examples: [{ plain: "hello", encoded: "BOu!rDZ" }],
    engine: ascii85Engine
  },
  {
    id: "adobe-ascii85",
    name: "Adobe Ascii85 — delimited form",
    shortName: "Adobe Ascii85",
    category: "Base85 family",
    status: "De facto standard",
    standard: "Adobe/PDF Ascii85 convention",
    alphabet: ASCII85_ALPHABET,
    padding: "partial final block rule",
    safeForUrls: false,
    supportsFiles: true,
    aliases: ["pdf ascii85", "adobe base85"],
    tags: ["pdf", "postscript", "base85"],
    summary: "Ascii85 wrapped in Adobe-style <~ and ~> delimiters, common in PostScript/PDF contexts.",
    canonicalRules: ["Output is wrapped with <~ and ~>.", "The zero group shorthand 'z' is supported.", "Whitespace is ignored when decoding."],
    examples: [{ plain: "hello", encoded: "<~BOu!rDZ~>" }],
    engine: adobeAscii85Engine
  },
  {
    id: "z85-zeromq",
    name: "Z85 — ZeroMQ Base85 specification",
    shortName: "Z85",
    category: "Base85 family",
    status: "Stable specification",
    standard: "ZeroMQ RFC 32/Z85",
    sourceUrl: "https://rfc.zeromq.org/spec/32/",
    alphabet: Z85_ALPHABET,
    padding: null,
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["zeromq base85"],
    tags: ["stable spec", "base85", "zeromq"],
    summary: "Z85 represents binary data as printable text and requires 4-byte input blocks / 5-character output blocks.",
    canonicalRules: ["Encoding input length must be divisible by 4 bytes.", "Decoding input length must be divisible by 5 characters.", "No padding is defined by the Z85 specification."],
    examples: [{ plain: "test", encoded: "By/Jn" }],
    engine: z85Engine
  },
  {
    id: "rfc1924-ipv6-base85",
    name: "RFC 1924 IPv6 Base85 — 16-byte compact form",
    shortName: "RFC1924 IPv6 Base85",
    category: "Base85 family",
    status: "Official standard",
    standard: "RFC 1924",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc1924",
    alphabet: RFC1924_ALPHABET,
    padding: null,
    safeForUrls: false,
    supportsFiles: false,
    aliases: ["ipv6 base85"],
    tags: ["official", "ipv6", "base85"],
    summary: "RFC 1924 defines a compact Base85 representation for exactly 128 bits, matching an IPv6 address length.",
    canonicalRules: ["Input must be exactly 16 bytes.", "Output must be exactly 20 characters.", "This page intentionally does not claim arbitrary raw Base85 is RFC 1924 canonical."],
    examples: [{ plain: "00000000000000000000000000000000", inputMode: "hex", encoded: "00000000000000000000" }],
    engine: rfc1924Engine
  },
  {
    id: "base91",
    name: "basE91 — dense printable ASCII encoding",
    shortName: "basE91",
    category: "Dense printable encodings",
    status: "Published reference",
    standard: "Joachim Henke basE91 reference algorithm",
    sourceUrl: "https://base91.sourceforge.net/",
    alphabet: BASE91_ALPHABET,
    padding: null,
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["base91", "base 91"],
    tags: ["dense", "printable", "rare"],
    summary: "basE91 is a high-density printable ASCII binary-to-text encoding with variable 13/14-bit packing.",
    canonicalRules: ["No padding is used.", "The reference alphabet contains 91 printable ASCII characters.", "Strict mode rejects characters outside the basE91 alphabet."],
    examples: [{ plain: "hello", encoded: "TPwJh>A" }],
    engine: base91Engine
  },
  {
    id: "base2048",
    name: "Base2048 — qntm reference implementation",
    shortName: "Base2048",
    category: "Rare Unicode lab",
    status: "Experimental reference",
    standard: "qntm/base2048 reference implementation",
    sourceUrl: "https://github.com/qntm/base2048",
    padding: "reference-specific",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["unicode base2048"],
    tags: ["unicode", "rare", "experimental"],
    summary: "Unicode high-radix encoding optimized around code-point-limited text contexts. Included only through the reference npm implementation.",
    canonicalRules: ["Uses the qntm reference package instead of a handwritten approximation.", "Treat as experimental/reference, not an RFC standard.", "Best compared by code-point count, not raw UTF-8 byte size."],
    examples: [],
    caveats: ["This encoder is intentionally labeled experimental/reference so users do not confuse it with RFC encodings."],
    engine: makeRarePackageEngine("base2048")
  },
  {
    id: "base32768",
    name: "Base32768 — qntm reference implementation",
    shortName: "Base32768",
    category: "Rare Unicode lab",
    status: "Experimental reference",
    standard: "qntm/base32768 reference implementation",
    sourceUrl: "https://github.com/qntm/base32768",
    padding: "reference-specific",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["unicode base32768"],
    tags: ["unicode", "utf16", "rare"],
    summary: "Unicode high-radix encoding optimized for UTF-16-encoded text. Included through the reference npm implementation.",
    canonicalRules: ["Uses the qntm reference package instead of a handwritten approximation.", "Treat as experimental/reference, not an RFC standard.", "Useful for Unicode-clean text channels, not general URL strings."],
    examples: [],
    engine: makeRarePackageEngine("base32768")
  },
  {
    id: "base65536",
    name: "Base65536 — qntm reference implementation",
    shortName: "Base65536",
    category: "Rare Unicode lab",
    status: "Experimental reference",
    standard: "qntm/base65536 reference implementation",
    sourceUrl: "https://github.com/qntm/base65536",
    padding: "reference-specific",
    safeForUrls: false,
    supportsFiles: true,
    recommended: true,
    aliases: ["unicode base65536", "base 65536"],
    tags: ["unicode", "utf32", "rare", "seo"],
    summary: "Rare Unicode binary-to-text encoding that maps two bytes per selected Unicode code point through the reference package.",
    canonicalRules: ["Uses the qntm reference package instead of a handwritten approximation.", "Treat as experimental/reference, not an RFC standard.", "May look short by character count while being larger in UTF-8 bytes."],
    examples: [],
    caveats: ["For normal web APIs and URLs, Base64/Base64url is usually the correct standard choice."],
    engine: makeRarePackageEngine("base65536")
  },
  {
    id: "base36",
    name: "Base36 — uppercase alphanumeric radix",
    shortName: "Base36",
    category: "Custom / numeric",
    status: "De facto standard",
    standard: "Common radix-36 convention: 0-9 A-Z",
    alphabet: BASE36,
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["radix36", "base 36"],
    tags: ["ids", "numeric", "url"],
    summary: "Base36 is a compact uppercase alphanumeric radix often used for IDs and number conversion.",
    canonicalRules: ["This implementation uses uppercase 0-9 A-Z alphabet order.", "Leading zero bytes are encoded as leading '0' characters.", "No padding is used."],
    examples: [{ plain: "hello", encoded: "5PZCSZU7" }],
    engine: base36Engine
  },
  {
    id: "base62",
    name: "Base62 — alphanumeric ID encoding",
    shortName: "Base62",
    category: "Custom / numeric",
    status: "De facto standard",
    standard: "Common alphanumeric radix convention: 0-9 A-Z a-z",
    alphabet: BASE62,
    padding: null,
    safeForUrls: true,
    supportsFiles: true,
    aliases: ["short url base62", "radix62"],
    tags: ["ids", "url", "shortener"],
    summary: "Base62 is commonly used for compact URL IDs and public identifiers.",
    canonicalRules: ["This implementation uses alphabet order 0-9, A-Z, a-z.", "Leading zero bytes are encoded as leading '0' characters.", "No padding is used."],
    examples: [{ plain: "hello", encoded: "7tQLFHz" }],
    engine: base62Engine
  }
];

export const categories = categoryOrder.filter((category) => encodingSpecs.some((item) => item.category === category));

export function getEncodingById(id: string): EncodingSpec | undefined {
  return encodingSpecs.find((spec) => spec.id === id);
}

export function getRecommendedEncodings(): EncodingSpec[] {
  return encodingSpecs.filter((spec) => spec.recommended);
}
